### ISSUE TITLE
Trying to load p5 with requirejs

### ISSUE THREAD

**Issue by visualisierte** [lmccart/p5.js#309]
Hello, i need a little bit of help. I am trying to load p5 as a AMD with requirejs. [Code example](https://github.com/visualisierte/middleman-template/blob/backbonejs/source/js/app/main.js)

When i try this, i get the following Errors in the Browser console:
> Uncaught ReferenceError: reqwest is not defined p5.js:2879

The p5 Object is undefined.

Thank you!

**Comment by MlleDR** [comment]
Won't this help ? https://github.com/rjbultitude/p5-requirejs-demo

**Comment by limzykenneth** [comment]
@MlleDR this is pretty old issue now and the library has changed considerably since. If you are encountering similar issue please open a new issue as this issue is closed and no longer relevant. Thanks.
