### ISSUE TITLE
node.js (commonJs) integration

### ISSUE THREAD

**Issue by z3a** [lmccart/p5.js#311]
Hi!

I'm just playing with the code (great work btw!) and I'd like to introduce p5.js into my workflow in which [Browserify](http://browserify.org) is the main tool that I use to write code using commonJs like modules. Currently I can use [browserify-shim](https://github.com/thlorenz/browserify-shim) to expose p5 as a module in my code, but it'd be pretty sweet to just npm install it and start using it as any other node.js module.

Is there any plan to support something like [UMD](https://github.com/umdjs/umd) or any other strategy  in order to make this library more easily integrated with any js loader?

**Comment by lmccart** [comment]
fixed with https://github.com/lmccart/p5.js/pull/483
