### ISSUE TITLE
reading local files selected by user

### ISSUE THREAD

**Issue by shiffman** [lmccart/p5.js#370]
Picking up on the discussion of #40 I created two examples based off of this [html5rocks tutorial](http://www.html5rocks.com/en/tutorials/file/dndfiles/).

1. [file select menu](https://github.com/shiffman/Programming-from-A-to-Z-F14/blob/master/week1/05_fileinput_p5/03_loadFile_Menu/sketch.js) -- this example opens a menu for a user to select a file (or files).
2.  [drag and drop file](https://github.com/shiffman/Programming-from-A-to-Z-F14/blob/master/week1/05_fileinput_p5/04_loadFile_DragDrop/sketch.js) -- this allows a user to drag a file onto a div to be read.

Do we want to consider adding this functionality to p5.dom?  Something along the lines of. . . 

```
var fileinput = createFileInput();
fileinput.readFile(process);

function process(file, data) {
  console.log(file.name + ' ' + file.type + ' ' + file.size + ' bytes');
  console.log("content: " + data);
}
```

The above assumes text data but I imagine there could be some hooks for images or other data formats, etc.

**Comment by shiffman** [comment]
Ok, I took another pass over this.  Here is the current status.

```
var fileSelect = createFileInput(gotFile);
```

An optional second argument specifies if you want to allow the user to select multiple files.

```
var fileSelect = createFileInput(gotFile, 'multiple');
```

I kept createX b/c the function is creating a new DOM element.  It's an input element with `type = 'file';`.   I would prefer something more succinct but can't think of anything.

The argument it takes is a callback which receives a `p5.File` object, a thin wrapper of native `File`.  Native HTML loads the file content with a separate callback, but I'm oversimplifying and assuming that ever file the user selects should be loaded and both the file metadata and contents are embedded in the `p5.File` object.  If the user selects multiple files the callback will be triggered multiple times (as each files loads).

```
function gotFile(file) {
  var fileDiv = createDiv(file.name + ' ' + file.type + ' ' + file.subtype + ' ' + file.size + ' bytes');
  // Check what kind of file it is
  if (file.type === 'image') {
    // Make an Image DOM element
    var img = createImg(file.data);
  } else if (file.type === 'text') {
    // Pull out some text, etc.
    createDiv(file.data);
  }
}
```

An alternative would be to pass in the native JS File object and a variable that holds the data, i.e.

```
function gotFile(file, data) {
  var fileDiv = createDiv(file.name + ' ' + file.type + ' ' + file.subtype + ' ' + file.size + ' bytes');
  // Check what kind of file it is
  if (file.type.indexOf('image') > -1) {
    // Make an Image DOM element
    var img = createImg(data);
  } else if (file.type.indexOf('text') > -1) {
    // Pull out some text, etc.
    createDiv(data);
  }
}
```

I haven't submitted a pull request yet.  Thoughts / comments?  I'm sure this is missing a lot but it's a start.

Branch is here: https://github.com/shiffman/p5.js/tree/selectfileinput

**Comment by lmccart** [comment]
ah, my mistake with the naming. `createFileInput` makes sense to me, as it's creating an input element and the file part specifies which type.

I think embedding the metadata and content in the file object makes sense, I think passing both file and data would be confusing for the user. does this cause any issues with performance or seem wrong for any other reason?

**Comment by shiffman** [comment]
First pass is implemented. Will leave this open for now.  To do:

* [ ] check documentation
* [ ] add example?
* [ ] work on drag and drop div

**Comment by shiffman** [comment]
I've now implemented functionality in p5.Element for a div you can drag files onto.  A full example would look like:

```javascript
  var dropZone = createDiv('Drop files here');
  dropZone.dragOver(callback1);
  dropZone.dragLeave(callback2);
  dropZone.drop(callbackDrop, callbackFileLoaded);
}
```

But a lot is optional and even just this will work:

```javascript
  var dropZone = createDiv('Drop files here');
  dropZone.drop(callbackFileLoaded);
}
```

This probably needs some finesse, comments / thoughts welcome.  There's also an example in `addons/file_input_div`.

**Comment by shiffman** [comment]
Some open items I need to look still.

* [ ] check if File API available in drop code
* [ ] documentation / examples on p5js.org?

**Comment by lmccart** [comment]
this is awesome. I made a little tweetable gist/gif.
https://gist.github.com/lmccart/c9109a9027ef5c99efa1

once the documentation is on the website I can add links to the specific functions in the ref and tweet.

**Comment by shiffman** [comment]
Fixed some things and documentation is now inline.  Will submit an example for p5js.org next.  Then this should be able to be closed.

**Comment by lmccart** [comment]
woohoo!
