### ISSUE TITLE
frameCount is skipping its count at random times!

### ISSUE THREAD

**Issue by GoToLoop** [lmccart/p5.js#406]
http://p5js.org/reference/#/p5/frameCount is supposed to represent how many times **draw()** was called back. But it's erratically failing at that!  :japanese_ogre: Here's a sketch suffering from it:  :neckbeard:

http://forum.processing.org/two/discussion/7809/creategraphics-and-framerate-can-you-have-a-different-value-per-canvas

```Processing
// forum.processing.org/two/discussion/7809/
// creategraphics-and-framerate-can-you-have-a-different-value-per-canvas

// 2014/Oct/26 by GoToLoop

const FPS = 60, INTERVAL = FPS*3; // each 3 seconds
var pg, count = 0;

function setup() {
  createCanvas(600, 400);
  frameRate(FPS).smooth().imageMode(CORNER);

  textAlign(CENTER), textStyle(BOLD), textSize(0200);
  fill(255), noStroke();

  pg = createGraphics(width, height>>1);
  pg.textAlign(CENTER), pg.textStyle(ITALIC), pg.textSize(060);
  pg.fill(0), pg.noStroke();
}

function draw() {
  background(0);
  text(frameCount/FPS|0, width>>1, height - (height>>3));

  if (frameCount%INTERVAL == 0)  updatePG(pg);
  image(pg, 0, 0);
}

function updatePG(pg) {
  const r = random(0400)|0, g = random(0400)|0, b = random(0400)|0;
  pg.background(r, g, b);

  pg.text("R : " + r + ", G : " + g + ", B : " + b
    , pg.width>>1, pg.height/1.8);
  pg.text(count + "\t\t\t" + 3*count++, pg.width>>1, pg.height/1.1);
}
```
It's supposed to **updatePG()** each 3 seconds -> `frameCount%INTERVAL == 0`. 
However, _frameCount_ sometimes skip counts and test above fails! :grimacing:

**Comment by eyaler** [comment]
i can recreate random frameCount skips with:

var frame=0;
function setup() {
}

function draw() {
  if (frame!=frameCount && frame<100)
  {
    print(frame + " " + frameCount);	
  }
  frame++;
}

this show randoms skips. e.g.:
test.js:9 6 7
test.js:9 7 8
test.js:9 8 9
test.js:9 9 10
...
test.js:9 81 82
test.js:9 82 83
test.js:9 83 85
test.js:9 84 86
test.js:9 85 87

**Comment by hamoid** [comment]
Maybe part of this could be used to write a test

```javascript
var nextFrameCount = 0, errors = 0;
function draw() {
    if(frameCount != nextFrameCount) {
        console.log("expected " + nextFrameCount + " but got " + frameCount);
        errors++;
    }
    nextFrameCount = frameCount + 1;
    
    if(errors > 20) {
        noLoop();
    }
}
```

**Comment by shiffman** [comment]
I just ran into this issue porting an example.  `frameCount` is currently increased in `this_runFrames` [core.js](https://github.com/lmccart/p5.js/blob/master/src/core/core.js#L293), however, if I move it to `this._draw` the problem is resolved.  @lmccart I can submit a pull request but wanted to check with you first.

**Comment by lmccart** [comment]
ah great, yes please do, thanks!
