### ISSUE TITLE
helper functions for URL and query string

### ISSUE THREAD

**Issue by shiffman** [lmccart/p5.js#459]
With several student projects this week there was a need to grab the window location (`window.location.href`) and parse out elements.  I haven't thought this through yet but I would like to add some helper functions to p5 for this purpose.  For example, let's say the url is something like

```
http://someserver.com/path/to/something/?val1=10&val2=11
```

I'm imagining.

```
var url    = getURL();         // 'http://someserver.com/path/to/something/?val1=10&val2=11'    
var path   = getURLPath();     // ['path','to','something','?val1=10&val2=11'];
var params = getURLParams();   // { val1: '10', val2: '11'}
```

Thoughts, comments, etc. welcome.

**Comment by lmccart** [comment]
closing this since we've got them in there and I haven't heard any issues with the methods as they stand, but anyone please feel free to reopen or comment if you have suggestions in this area.
