### ISSUE TITLE
Instance mode - clarify ambiguous terminology ("sketch" vs "sketch")

### ISSUE THREAD

**Issue by wxactly** [lmccart/p5.js#473]
Using "instance mode", like in [the example](http://p5js.org/learn/examples/Instance_Mode_Instantiation.php):
```javascript
var s = function( sketch ) {

  var x = 100; 
  var y = 100;

  sketch.setup = function() {
    sketch.createCanvas(700, 410);
  };

  sketch.draw = function() {
    sketch.background(0);
    sketch.fill(255);
    sketch.rect(x,y,50,50);
  };
};

var myp5 = new p5(s);
```
I've come to the understanding that a p5 instance (`new p5()`) is called a "sketch". So in the example above, I would call `myp5` the "sketch". I also understand that within the function block, `sketch` refers to the same object that `myp5` does, so I would also call `sketch` the "sketch".

What would I call the function `s`? Looking into the p5 source, the argument is named `sketch`. That seems super confusing. Are my assumptions about the term "sketch" incorrect, as it relates to instance mode? Can anyone help to clarify this ambiguous terminology? (Or clarify my understanding of how instance mode works?) Currently it seems like I have to instantiate my sketch with a sketch that gets passed a sketch...

**Comment by GoToLoop** [comment]
Term "sketch" is the nickname Processing framework calls its code:
https://github.com/processing/processing/wiki/FAQ#what-is-the-sketchbook-what-do-you-mean-by-sketches

In the example above, *sketch* is simply the name of the local variable.

**Comment by wxactly** [comment]
Ah, that helps - thanks for setting me straight. Yeah, it actually makes a lot more sense to call `s` the "sketch", since that's what defines what p5 _does_... And since that's what the p5 source code calls it internally, it makes the system easier to understand by keeping the terminology consistent. (It looks like this is fairly consistent with Processing as well? Based on the link from @GoToLoop.)

So would it be less confusing to update the instance mode example that I linked to be consistent with how it uses the word "sketch"? Or use some other language like "environment" or "runner"? What feels right?

**Comment by lmccart** [comment]
thanks everyone for clarifying this point, you're right @wxactly it is a bit ambiguous. @brysonian describes it correctly.  maybe it could be more clearly written like:

```javascript
var sketch = function( s ) {

  var x = 100; 
  var y = 100;

  s.setup = function() {
    s.createCanvas(700, 410);
  };

  s.draw = function() {
    s.background(0);
    s.fill(255);
    s.rect(x,y,50,50);
  };
};

var myInstance = new p5(sketch);
```

does this line up with how people are currently thinking about things?

**Comment by wxactly** [comment]
Yeah that definitely helps, @lmccart... but if I'm explaining this to someone, what would I say `s` stands for? (Sketch? :|)

When I use Processing.js in "instance mode", my sketch looks something like this:
```javascript
var sketch = function(p) {
  p.setup = function() {
    //...
  };

  p.draw = function() {
    p.background(255);
    //...
  };
};

var p = new Processing(canvas, sketch);
```
Where `p` stands for "processing". (You [could name it `processing`](http://processingjs.org/articles/jsQuickStart.html#javascriptonlyprocessingcode) too, of course... I just don't like typing all those letters on every line of my sketch.) ;) This seems very clear to me.

In a perfect world, I might suggest something like this for p5.js:
```javascript
var sketch = function(p5) {
  p5.setup = function() {
    //...
  };

  p5.draw = function() {
    p5.background(255);
    //...
  };
};

var p5 = new P5(sketch);
```
Where `P5` is the "p5.js class" and `p5` is the "p5.js instance". This would be consistent with [typical javascript style](https://github.com/felixge/node-style-guide#use-uppercamelcase-for-class-names) and it would help disambiguate the symbols quite a bit, IMO.

Maybe a middle of the road approach would be to just use `p` as the p5 instance passed to the sketch, or `myp5` or something that makes it clear that you can name the instance whatever you want.

**Comment by wxactly** [comment]
I made a pull request to address the specific example in this issue. All of this is still open for discussion as far as I'm concerned... Please let me know if you have other ideas about how to name the variables in these examples. I just felt some ownership for this issue since I started it - I didn't want to just leave this to rot.

There is some precedent for this style, e.g. https://github.com/lmccart/p5.js/blob/master/examples/instantiation-instance/case1/sketch.js

If people like the style I used in lmccart/p5.js-website#79, I will make a second PR on this repo to address these examples as well: https://github.com/lmccart/p5.js/tree/master/examples/instantiation-instance

Otherwise, let me know what you think. Thanks

**Comment by lmccart** [comment]
great thanks!
