### ISSUE TITLE
background() and set() affected by transformations

### ISSUE THREAD

**Issue by eyaler** [lmccart/p5.js#474]
In processing background() and set() are not affected by preceding transformations such as scale(), translate() and rotate(). in p5js they are, where i would expect an identical behavior to processing

compare processing:
void setup() {
  size(640, 480);
  background(0);
}

void draw() {
  scale(0.5);
  rotate(20);
  background(100);
}
  
p5js:
function setup() {
  createCanvas(640,480);
  background(0);
}

function draw() {
   scale(0.5);
   rotate(20);
   background(100);
}

**Comment by GoToLoop** [comment]
They're not supposed to! Since they manipulate `pixels[]` itself!

**Comment by lmccart** [comment]
hey @eyaler thanks for reporting this! I believe `background()` should not be affected by transforms any longer, but I had trouble reproducing the issue with `set()`. Would you mind posting an example that demonstrates the behavior? I was using the one below but it seems to work ok.
```javascript
function setup() {
  createCanvas(640,480);
  fill(200);
  background(0);
}

function draw() {
  scale(0.5);
  rotate(20);
  for (var i=0; i<100; i++) {
    for (var j=0; j<100; j++) {
      set(i, j, 255);
    }
  }
  updatePixels();
  rect(0, 0, 100, 100); // draws transformed for comparison
}
```

**Comment by eyaler** [comment]
thanks. i've seen this with set(0,0,img)

var img;

function setup() {
  createCanvas(720, 400);
  img = loadImage("img/IMG_2271.JPG");
}

function draw() {
  scale(0.1);
  set(0,0,img);
}
