### ISSUE TITLE
no way to specify camera fps

### ISSUE THREAD

**Issue by eyaler** [lmccart/p5.js#476]
in processing one can specify to camera fps by:
Capture cam = new Capture(this, w, h, cam_fps);

in p5js:
var capture = createCapture(VIDEO);
capture.size(w, h);
// no way to specify fps...

**Comment by lmccart** [comment]
hey thanks for reporting this one, I'm going to close this issue as I think this other one covers it more generally. https://github.com/lmccart/p5.js/issues/495
