### ISSUE TITLE
devicePixelScaling() only works in setup function

### ISSUE THREAD

**Issue by eyaler** [lmccart/p5.js#479]
devicePixelScaling() only works in setup function, when called from draw function we get an error. if it is not inteded to be called from draw, lets mention that in the docs

**Comment by lmccart** [comment]
actually, this is working ok for me, what error are you getting?

```javascript
var dps = true;

function setup() {
  createCanvas(100, 100);
}

function draw() {
  background(255, 0, 100);
  ellipse(width/2, height/2, 100, 100);
}

function mousePressed() {
  dps = !dps;
  devicePixelScaling(dps); // turn into comment to overcome error
}
```

**Comment by eyaler** [comment]
@imccart, your example works fine. but if i move devicePixelScaling(dps); to the first line of draw() i get an unspecified error:

 <error> p5.js:654
 p5.Graphics.resize p5.js:4154
 p5.resizeCanvas p5.js:2136
 p5.devicePixelScaling test.js:8
 draw p5.js:4869
 p5.redraw p5.js:4156
