### ISSUE TITLE
devicePixelScaling() with image.loadPixels() gives error

### ISSUE THREAD

**Issue by eyaler** [lmccart/p5.js#480]
if calling devicePixelScaling(), a subsequent call to image.loadPixels() gives error: Uncaught TypeError: Cannot read property 'loadPixels' of undefined

var capture;

function setup() {
  devicePixelScaling(false); // turn into comment to overcome error
  capture = createCapture(VIDEO);
  // alternatively: capture = loadImage("image.jpg");
}

function draw() {
    capture.loadPixels(); // gives error
}

**Comment by lmccart** [comment]
thanks for all the bug reports, these are very helpful!
