### ISSUE TITLE
Whole typography group API doesn't work anymore!

### ISSUE THREAD

**Issue by GoToLoop** [lmccart/p5.js#484]
http://p5js.org/reference/#group-Typography
Just tried some code w/ typography functions and pasted in http://p5js.org site and found out it crashes!
Bug message: "TypeError: this.drawingContext is undefined"

http://p5js.org/reference/#/p5/shearX & http://p5js.org/reference/#/p5/shearY
Also found out by chance that both **shearX()** & **shearY()** aren't working either:
"TypeError: this.tan is not a function"

**Comment by lmccart** [comment]
hi @GoToLoop which version of the library are you using, seems to be working ok for me with v0.3.16.

**Comment by GoToLoop** [comment]
Never used any version. Always used http://p5js.org site reference.

**Comment by lmccart** [comment]
all seem to look ok, can you tell me which page specifically and which browser you're using?

**Comment by GoToLoop** [comment]
Right now I'm @ a 64-bit Win7. These browsers failed:

* Waterfox 34.0.1 (based on Firefox) (64-bit)
* Slimjet 2.1.6.0 (based on Chromium 38.0.2125.104) (64-bit)

All of them just halts & displays: "loading..." 
However, used more browsers and surprisingly they all worked normally:

* Palemoon 12.3 (based on Firefox) (32-bit)
* SRWare Iron (based on Chromium 39.0.2100.0) (32-bit)
* Qupzilla 1.8.5 (based on WebKit) (32-bit)
* Opera 12.17 (based on the deprecated Presto engine) (64-bit)
* IE11 (64-bit)

Seems like when a Firefox or Chromium based browser happens to be 64-bit it fails here! O_o

**Comment by GoToLoop** [comment]
Oh, never mind! After clearing all cache from both of those failing browsers, they re-worked again!  
Sorry for bothering you!  =(

**Comment by lmccart** [comment]
great, glad to hear it's ok :)
