### ISSUE TITLE
loadTable() not working properly in preload?

### ISSUE THREAD

**Issue by shiffman** [lmccart/p5.js#486]
With a simple CSV like so:

```
name,num
test,1
another,2
```

the following works:

```
function setup() {
  createCanvas(600, 400);
  loadTable('data.csv','header',loaded);
}

function loaded(table) {
  data = table;
  for (var i = 0; i < table.rows.length; i++) {
    console.log(data.rows[i].get('name'));
  }
}
```

However, the following does not:

```
function preload() {
  data = loadTable('data.csv','header');
}

function setup() {
  createCanvas(600, 400);
  for (var i = 0; i < table.rows.length; i++) {
    console.log(data.rows[i].get('name'));
  }
}
```

**Comment by lmccart** [comment]
looks like something is loading, but it's not taking into account the header line. so if I log the table object in both cases at the beginning of the `loaded()` function, for the callback case I see an object with 3 rows with the header labels associated with the data. whereas with the preload case I see an object with 4 rows (the first row is the headers), and no header labels associated, causing `.get('name')` to fail.

**Comment by tintinsnowy** [comment]
@shiffman .I'm working on it. Here is the thing. When the csv file more than 50kB or so, the p5.js works very slowly. BTW what's the maximal size of CSV which can be processed. When I tried a file with 96kb size, the p5.js shows that only part of the data has been processed.

thanks

**Comment by limzykenneth** [comment]
@tintinsnowy This looks like a pretty old issue and might have been solved already. The file loading functions are partially rewritten recently in 0.5.8 so it might not apply as well. Can you open a new issue for the CSV file size problem and provide a sample of the CSV file that either loaded too slowly or loaded incorrectly? Thanks.
