### ISSUE TITLE
easy access to "step" attribute for slider

### ISSUE THREAD

**Issue by shiffman** [lmccart/p5.js#487]
The default "step" for an HTML5 input element is 1.  This creates some funny behavior with p5 code like:

```
var slider = createSlider(0, 1, 0.5);
```

This is easily fixed by saying:

```
var slider = createSlider(0, 1, 0.5);
slider.elt.step = 0.01;
```

I think we should add access to `step` as an optional constructor arg or as a method for p5.element.  @lmccart what do you think?  I'm happy to implement this if that would be helpful.

**Comment by lmccart** [comment]
yes, definitely, I think this makes sense, go for it!

**Comment by shiffman** [comment]
Ok, made this change and submitted a pull request. 

1. Does it make any sense to add any methods for changing the `min`, `max`, `step` attributes after the fact?  Perhaps not since needing to do so is rare and it can always be done via `elt`.

```
var slider = createSlider(0, 5, 50, 0.5);

// and later?
slider.set(0, 1, 0.5, 0.01);

// or
slider.range(0, 1);
slider.step(0.01);
slider.value(0.5); // already there
```

2. I am tempted to do something fancy and calculate an appropriate step based on the min/max, but thinking about it we should stay true to native HTML which defaults to 1.

**Comment by lmccart** [comment]
I think your intuition makes sense (leave out the extra methods and let people access through elt). I'm wondering if we need a name change for that though. would element or some other word be better?

agree also that sticking with 1 makes sense.

**Comment by shiffman** [comment]
I wonder if we should keep `elt` but just make a method `element()` that returns the native DOM element?  Maybe that's silly.   I agree that right now it feels like a hidden, undocumented thing.  The larger question is how much it should be exposed and part of the API or a think you know about it you want to do more custom, native stuff.  I'll close this for now and we can re-open a new thread to the extent you want to revisit this issue?
