### ISSUE TITLE
this.drawingContext.resetTransform is not a function

### ISSUE THREAD

**Issue by jarav** [lmccart/p5.js#488]
this.drawingContext.resetTransform is not a function --
error in Firefox 35.0, Ubuntu 14.04, p5.js v0.3.16 January 15, 2015

In FF the drawing context does not seem to have this function. No problem in Google-Chrome 39.

**Comment by GoToLoop** [comment]
Perhaps it's the same that hapṕened to me? https://github.com/lmccart/p5.js/issues/484

**Comment by lmccart** [comment]
fixed with https://github.com/lmccart/p5.js/pull/493
