### ISSUE TITLE
screen does not clear completely in mobile browser

### ISSUE THREAD

**Issue by jarav** [lmccart/p5.js#489]
I am running a rather simple p5js sketch with noLoop. The screen is redrawn only on a slider event. In google-chrome under Moto E and Nexus 7, 2012 version, the screen is not getting cleared completely with the background command. Bits and pieces of the previous screen remain.

**Comment by hamoid** [comment]
Could you share a minimal example?

**Comment by jarav** [comment]
@hamoid 
Just now I downloaded p5.js v0.3.16 January 29, 2015 and tried it out. The problem seems to have gone away. I had faced the problem with p5.js v0.3.16 January 15, 2015.
