### ISSUE TITLE
add a "sync" option so that a p5 instance can be created an used right away

### ISSUE THREAD

**Issue by kevinb7** [lmccart/p5.js#490]
I'm working on a branch of Khan Academy's live-editor which replaces processing-js with p5.js.  The live-editor creates a processing instance and then runs user code using a ```with``` statement inside of a function created with ```new Function(code)```.  The issue I ran into when converting to p5.js is that the code path in live-editor is synchronous.  

I modified the p5 constructor to look like ```  var p5 = function(sketch, node, sync) { ... }``` and change the code at the bottom of the constructor that calls ```this._start()``` to look like this:

```
if (sync) {
      this._start();
    } else {
      if (document.readyState === 'complete') {
        this._start();
      } else {
        window.addEventListener('load', this._start.bind(this), false);
      }
    }
```

All of the existing tests pass.  I'll write some additional tests before submitting a pull request.
Here's a link to the change set: https://github.com/kevinb7/p5.js/commit/f4d349fd8fa4801f620b00cb4ebc5057bfa14f2e

**Comment by wxactly** [comment]
Would it be possible to *always* use a synchronous initialization path? Or is there some reason it's implemented async....

It's similarly awkward to unit test code written against p5... you can't just do this:

```javascript
var myp5 = new p5(function(sketch) {}, element);
expect(element.find('canvas')[0]).toBeTruthy();
```

You have to write something like:

```javascript
runs(function() {
  var myp5 = new p5(function(sketch) {}, element);
});

waitsFor(function() {
  return element.find('canvas')[0];
});

runs(function() {
  expect(element.find('canvas')[0]).toBeTruthy();
});
```

**Comment by lmccart** [comment]
hi @kevinb7 this sounds good. it might be good if it could also support `var p5 = function(sketch, sync) { ... }` by checking the type of the second arg.

**Comment by GoToLoop** [comment]
This is looking more & more like **Promise**'s resolve & reject parameters:   :D
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by kevinb7** [comment]
@lmccart you bet!
