### ISSUE TITLE
loadImage should have an error callback

### ISSUE THREAD

**Issue by kevinb7** [lmccart/p5.js#491]
It would be nice if loadImage had an error callback.  This would make the function signature look like this:
```
loadImage(path, [successCallback], [failureCallback])
```
The changes to loadImage would be minimal.  It just needs an ```onerror``` handler to call ```failureCallback```.

**Comment by lmccart** [comment]
hey this sounds like a great idea

**Comment by GoToLoop** [comment]
This is looking more & more like **Promise**'s resolve & reject parameters:   :D
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by kevinb7** [comment]
@GoToLoop I thought about promises, but to hit all of the browsers you'll need a polyfill... it's easy enough for people to promisify (or denodeify) this function.  If you're using Q for promises, it actually has a static method called ```denodeify```.

@lmccart cool... btw, awesome library!
