### ISSUE TITLE
Plugins break when used with browserify

### ISSUE THREAD

**Issue by brysonian** [lmccart/p5.js#494]
Loading a plugin in browserify requires manually putting the p5 object on window:

```
var p5 = require("./p5.js");
window.p5 = p5;
require("./p5.dom.js");
```

Not sure what the most elegant solution here is. Here are a few approaches, all of which have some issues (note all of these assume using the instance method of passing a function to the p5 constructor, `s` is the function arg passed the sketch instance) :

```
var p5 = require("./p5.js");
var p5Dom = require("./p5.dom.js");
...
capture = p5Dom.createCapture(s.VIDEO);
```

or

```
var p5 = require("./p5.js");
p5.dom = require("./p5.dom.js");
...
capture = s.createCapture(s.VIDEO);
```
(this would put all dom methods on the p5.dom object)

or

```
var p5 = require("./p5.js");
require("./p5.dom.js")(p5);
...
capture = s.createCapture(s.VIDEO);
```
(plugin returns a function that you pass your p5 var to)

Thoughts/suggestions/preferences?

**Comment by kevinb7** [comment]
What if the DOM module did ```var p5 = require('p5');``` then was published as a UMD module?  That way people who are using requirejs would do something like ```define(["p5", "p5.dom"], function (p5) { ... });``` (or whatever the preferred style is) and people who are using plain old ```<script>``` tags would just add the script for p5.js and p5.dom.js in the right order.

**Comment by brysonian** [comment]
ahh that's the idea! got it working, PR coming later tonight.

one related though slightly OT question, does anyone know p5 is installed with npm if there is a clear way to find the path to the add ons? require('p5') works just fine, but i'm not sure if there is a mechanism for require'ing extra files.

**Comment by kevinb7** [comment]
It probably makes sense for the DOM plugin (and other plugins) to be separate modules that have ```p5``` as a dependency.  This is something that @lmccart should probably weigh in on.

**Comment by kevinb7** [comment]
@brysonian looking forward to the PR.

**Comment by kadamwhite** [comment]
@brysonian If I'm understanding your question right, you can require sub-modules within an NPM package by using relative paths from the root of the module: for example, if module `foo` has a file at `dir/bar.js`, you can require it with `require( 'foo/dir/bar' );`. Personally @kevinb7 I'd prefer to install one single dependency (that I know will be internally version-consistent) and to have to say `require( 'p5/lib/addons/p5.dom' )` than to have to install `p5-dom`, but that's just me.

**Comment by kevinb7** [comment]
@kadamwhite good point

**Comment by brysonian** [comment]
PR here: #509

**Comment by lmccart** [comment]
awesome thanks everyone! so this issue is resolved now, correct?

**Comment by brysonian** [comment]
Almost, need to do the same for sound, just haven't had a chance.

**Comment by lmccart** [comment]
ah got it. looping @therewasaguy in here, as p5.sound is built with grunt then a copy is placed in the p5 repo, so the changes will actually need to be made here: github.com/therewasaguy/p5.sound.

**Comment by therewasaguy** [comment]
Cool! For p5.sound I just added [these 'before' and 'after' fragments](https://github.com/therewasaguy/p5.sound/tree/master/fragments) to the build script. They do what @brysonian did for p5.dom.
