### ISSUE TITLE
fill in HSB color mode doesn't behave as expected with color objects

### ISSUE THREAD

**Issue by juansrx** [lmccart/p5.js#508]
Hello, I have this sample code:

function setup() {
  createCanvas(600, 600);
  colorMode(HSB, 360, 100, 100);
}

function draw()
{
	fill(90, 100, 100);
	rect(0,0,600,600);
}

I'm using p5 0.3.16 from the cloudfare cdn, and this is the result:

![image](https://cloud.githubusercontent.com/assets/5339082/5986878/d91b708e-a8dc-11e4-82ce-5228b18faf84.png)

But when I use

function draw()
{
	var c = color(90, 100, 100);
	fill(c);
	rect(0,0,600,600);
}

It looks like this:

![image](https://cloud.githubusercontent.com/assets/5339082/5986900/90aa5288-a8dd-11e4-9d5d-3e2eb0e4e553.png)

And I'm affraid that no matter the HSB combination, the color looks "blueish". ¿Do I have to use the tree parameter form in this case?. Thanks for your help.

**Comment by lmccart** [comment]
I believe this is fixed with https://github.com/lmccart/p5.js/pull/539
please reopen if you're still seeing issues!
