### ISSUE TITLE
Unable to predictably flip image from createCapture()

### ISSUE THREAD

**Issue by mlsptn** [lmccart/p5.js#525]
Hello,

I am trying to mirror the feed from the webcam using the following code:

`
var capture; 
 
function setup() {
    createCanvas(displayWidth,displayHeight);
    capture = createCapture(VIDEO);
    capture.size(displayWidth,displayHeight);
}
 
function draw() {
    push(); 
    translate(capture.width,0); 
    scale(-1.0,1.0); 
    image(capture,0,0); 
    pop();
}
`

For some reason, the mirroring only works about 1/2 times I run it. I'm using Firefox to test, on Mac OSX 10.10.

**Comment by lmccart** [comment]
well I didn't fix your issue yet but I am working on it: https://www.youtube.com/watch?v=rMh5e5mQNoI

**Comment by mlsptn** [comment]
!! 👀 🙊

**Comment by lmccart** [comment]
it seems like it could be related to this
http://stackoverflow.com/questions/18580844/firefox-drawimagevideo-fails-with-ns-error-not-available-component-is-not-av

I just tried adding the try..catch in there and it seems to fix the problem. will submit a patch soon.

**Comment by lmccart** [comment]
@mlsptn can you test with the newest p5.js file and check that this works when you get a chance?

**Comment by mlsptn** [comment]
@lmccart it works! thank you so much :)
