### ISSUE TITLE
mask inverted?

### ISSUE THREAD

**Issue by shiffman** [lmccart/p5.js#531]
I think the `mask()` function might be inverted.  Related to #121 I am porting a Processing example ("AlphaMask") and changed the `mask.jpg` to `mask.png` with an alpha channel mirroring the grayscale image.  However, the p5 result I'm seeing is inverted:

![screen shot 2015-02-11 at 3 18 52 pm](https://cloud.githubusercontent.com/assets/191758/6149528/56da10de-b201-11e4-96f8-a90fa48afb61.png)

Processing screen cap:

![screen shot 2015-02-11 at 3 19 26 pm](https://cloud.githubusercontent.com/assets/191758/6149535/621f27a4-b201-11e4-8983-507af8f63c12.png)

Is this correct HTML5 behavior and I should manually invert the pixels or is the `mask()` function inverted?

**Comment by shiffman** [comment]
Reference code is here: https://github.com/processing/processing-docs/tree/master/content/examples_p5/Basics/Image/Alphamask

**Comment by lmccart** [comment]
I can look deeper into it later, but from what I remember, p5.js uses the alpha channel rather than the black or blue or something that Processing uses... more here: https://github.com/lmccart/p5.js/issues/121

not sure if this explains the behavior you're seeing?

**Comment by shiffman** [comment]
Yes I already adjusted for this by moving the blue channel into the alpha channel in mask.png.  I'll dig into it too more.

**Comment by shiffman** [comment]
Ok, I can confirm that p5 is setting the alpha value to 0 when the alpha pixel value is white and to 255 when the pixel value is 0.  Using the original mask:

![screen shot 2015-02-11 at 3 54 00 pm](https://cloud.githubusercontent.com/assets/191758/6150266/45e7df7c-b206-11e4-9679-a1837ba2d6db.png)

And then if I do the following:

```
  imgInverted.loadPixels();
  imgMask.loadPixels();
  for (var i = 3; i < imgInverted.pixels.length; i+=4) {
    imgInverted.pixels[i] = 255-imgMask.pixels[i];
  }
  imgInverted.updatePixels();
```

I get:

![screen shot 2015-02-11 at 3 55 14 pm](https://cloud.githubusercontent.com/assets/191758/6150298/66c8af32-b206-11e4-8aa7-c45f261e2b1d.png)

I guess I am not sure if this is how it should work in order to mirror native canvas functionality or if this is a bug.  I'm happy to look into this more.

**Comment by kevinb7** [comment]
If the native canvas works differently from how Processing works then maybe there could be a option that people could use to select the behaviour they prefer.

**Comment by shiffman** [comment]
I dug into this more and I believe we should be using `destination-in` vs `destination-out` as the `globalCompositeOperation` in the `mask` function.  Neither is correct or incorrect but I think it's more intuitive for 255 to mean opaque and 0 to mean transparent.  We could certainly expose this as an option to the user but I think that may be overkill and anyone who needs this level of detail can work with the canvas operations directly. I'll submit a pull request.

**Comment by GoToLoop** [comment]
I agree! Alpha is level of opaqueness. The higher, the more opaque it gets!

**Comment by lmccart** [comment]
awesome, thanks!

closed with https://github.com/lmccart/p5.js/issues/531
